version: '3'


services:
  api-gateway:
    build: api_gateway/
    ports:
      - "5000:5000"
    depends_on:
      - books-service
      - users-service
    # - reviews-service
    # - transactions-service
    networks:
      - main-network

  books-db:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbBook
    networks:
      - main-network

  books-service:
    build: books_service/
    ports:
      - "5002:5000"
    environment:
      DATABASE_URL: postgresql://username:password@books-db:5432/dbBook
    depends_on:
      - books-db
    networks:
      - main-network

  users-db:
    image: postgres:12
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbUsers
    networks:
      - main-network

  users-service:
    build: users_service/
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: postgresql://username:password@books-db:5432/dbUsers
    depends_on:
      - users-db
    networks:
      - main-network

  # reviews-service:
  #   build: reviews_service/
  #   ports:
  #     - "5003:5000"
  #   networks:
  #     - main-network

  # transactions-service:
  #   build: transactions_service/
  #   ports:
  #     - "5004:5000"
  #   networks:
  #     - main-network

  web-interface:
    build: web_interface/
    ports:
      - "8000:8000"
    depends_on:
      - api-gateway
    networks:
      - main-network

networks:
  main-network:
    driver: bridge

volumes:
  pgdata: